# Generated by Django 5.2.4 on 2025-07-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='class_letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='class_number',
            field=models.CharField(blank=True, choices=[('5-sinf', '5-sinf'), ('6-sinf', '6-sinf'), ('7-sinf', '7-sinf'), ('8-sinf', '8-sinf'), ('9-sinf', '9-sinf'), ('10-sinf', '10-sinf'), ('11-sinf', '11-sinf')], default='5-sinf', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='info_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='students_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
