# Generated by Django 5.2.4 on 2025-07-08 18:24

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_city_alter_customuser_class_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='teachers_token',
            field=models.CharField(default=users.models.generate_token, max_length=256, unique=True),
        ),
    ]
