# Generated by Django 5.2.4 on 2025-07-09 16:27

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_schools_teachers_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='students_token',
            field=models.CharField(blank=True, default=users.models.generate_token, max_length=256, null=True),
        ),
    ]
