# Generated by Django 5.2.4 on 2025-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='see_password',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
