# Generated by Django 5.2.4 on 2025-07-09 16:27

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Darsning nomi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tests_count', models.IntegerField(default=0)),
                ('class_number', models.CharField(max_length=256)),
                ('author', models.CharField(blank=True, max_length=1024, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjects', verbose_name='Qaysi fan boyicha')),
            ],
            options={
                'verbose_name': 'Test bolimi',
                'verbose_name_plural': 'Test bolimlari',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=2)),
                ('answer_A', models.TextField()),
                ('answer_B', models.TextField()),
                ('answer_C', models.TextField()),
                ('answer_D', models.TextField()),
                ('_case', models.ForeignKey(default=main.models.latest_test_case, on_delete=django.db.models.deletion.CASCADE, to='main.testcase')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
    ]
