# Generated by Django 5.2.4 on 2025-07-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='author',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='class_number',
            field=models.CharField(choices=[('5-sinf', '5-sinf'), ('6-sinf', '6-sinf'), ('7-sinf', '7-sinf'), ('8-sinf', '8-sinf'), ('9-sinf', '9-sinf'), ('10-sinf', '10-sinf'), ('11-sinf', '11-sinf')], max_length=256),
        ),
    ]
