# Generated by Django 5.2.4 on 2025-07-10 05:06

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_testcase_author_alter_testcase_class_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='test_cases', to='main.tests', verbose_name='Savollar'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='_case',
            field=models.ForeignKey(default=main.models.latest_test_case, on_delete=django.db.models.deletion.CASCADE, related_name='test_set', to='main.testcase'),
        ),
    ]
